In [1]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
# Load the data into a DataFrame
data = pd.read_csv(filepath_or_buffer='final_data_only_tpm.csv')

# Split the data into features (X) and target variable (y)
X = data.drop('cancer_type', axis=1)
y = data['cancer_type']

# Split the data into training and validation sets
train_dataset, test_dataset = train_test_split(data, test_size=0.2, random_state=42)

data.head()

TSPAN6    TNMD      DPM1   SCYL3  C1orf112      FGR      CFH    FUCA2  \
0  19.7011  0.1125   46.1397  1.8913    0.2670  18.6466   4.3945  24.1591   
1  31.6275  0.0000   45.5189  2.8743    0.4744   4.2348   1.4145  60.8153   
2  35.9928  0.5207  108.0270  4.8134    0.8010   4.5446   3.2850  33.1630   
3  18.2605  0.0921   27.5398  2.3258    0.3473   4.5023   1.5078  47.2006   
4  68.8052  3.4134   88.0619  6.2415    1.2251   9.5310  30.6990  66.3841   

      GCLC     NFYA  ...  AC092910.4  AC073611.1  AC136977.1  AC078856.1  \
0   6.7242   9.4371  ...         0.0      0.0641         0.0      1.0888   
1  15.4309   7.5267  ...         0.0      0.0781         0.0      0.0000   
2  13.1085  12.1888  ...         0.0      0.1049         0.0      0.0000   
3  10.6721   5.0657  ...         0.0      0.1193         0.0      0.0000   
4  12.9370  20.1289  ...         0.0      0.1141         0.0      0.0000   

   AC008763.4  AL592295.6  AC006486.3  AL391628.1  AP006621.6  \
0         0.0      3.1977         0.0      0.0104      0.3953   
1         0.0     15.4262         0.0      0.0042      0.4094   
2         0.0     13.2312         0.0      0.1154      0.3050   
3         0.0      6.4516         0.0      0.0141      0.1416   
4         0.0     21.8857         0.0      0.0394      0.3547   

          cancer_type  
0  kidney chromophobe  
1  kidney chromophobe  
2  kidney chromophobe  
3  kidney chromophobe  
4  kidney chromophobe  

[5 rows x 60661 columns]

In [2]:
# Split the data into training and validation sets
import torch
# Split the data into features (X) and target variable (y)


map = {
    "kidney chromophobe": 0,
    "kidney renal papillary cell carcinoma": 1,
    "kidney renal clear cell carcinoma": 2,
}

data1 = data.copy()
data1['cancer_type'] = data1['cancer_type'].replace(map)

X = data1.drop('cancer_type', axis=1)
y = data1['cancer_type']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

X_train_tens = torch.tensor(X_train.values).float()
X_test_tens = torch.tensor(X_test.values).float()
y_train_tens = torch.tensor(y_train.values)
y_test_tens = torch.tensor(y_test.values)

data1.head()

y_test_tens

tensor([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 0, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2,
        2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 0, 0, 2, 1, 2, 1, 2, 2, 2, 0,
        1, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 0, 2, 1, 1, 2, 1, 2, 1, 1, 2, 0, 2, 2,
        0, 2, 1, 0, 0, 2, 2, 2, 0, 1, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2,
        2, 1, 0, 1, 1, 2, 2, 1, 0, 1, 0, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1,
        1, 2, 2, 0, 0, 1, 2, 1, 2, 2, 2, 2, 0, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2,
        2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 0, 0, 2, 0, 2, 1, 2, 1,
        2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2])

In [3]:
# # Import dependencies
# import torch
# import matplotlib.pyplot as plt
# from sklearn.datasets import make_blobs
# from sklearn.model_selection import train_test_split

# # Set the hyperparameters for data creation
# NUM_CLASSES = 4
# NUM_FEATURES = 2
# RANDOM_SEED = 42

# # 1. Create multi-class data
# X_blob, y_blob = make_blobs(n_samples=1000,
#     n_features=NUM_FEATURES, # X features
#     centers=NUM_CLASSES, # y labels 
#     cluster_std=1.5, # give the clusters a little shake up (try changing this to 1.0, the default)
#     random_state=RANDOM_SEED
# )

# # 2. Turn data into tensors
# X_blob = torch.from_numpy(X_blob).type(torch.float)
# y_blob = torch.from_numpy(y_blob).type(torch.LongTensor)
# print(X_blob[:5], y_blob[:5])

# # 3. Split into train and test sets
# X_train_tens, X_test_tens, y_train_tens, y_test_tens = train_test_split(X_blob,
#     y_blob,
#     test_size=0.2,
#     random_state=RANDOM_SEED
# )

# # 4. Plot data
# plt.figure(figsize=(10, 7))
# plt.scatter(X_blob[:, 0], X_blob[:, 1], c=y_blob, cmap=plt.cm.RdYlBu);

In [4]:
import torch.utils.data
import torch.nn as nn
from torch.utils.data import DataLoader

batch_size = 128

train_dataloader = DataLoader(
    dataset=train_dataset, batch_size=batch_size, shuffle=True
)
val_dataloader = DataLoader(dataset=test_dataset, batch_size=batch_size)

# Build model
class MultiClassificationModel(nn.Module):
    def __init__(self, input_features, output_features, hidden_units=8):
        """Initializes all required hyperparameters for a multi-class classification model.

        Args:
            input_features (int): Number of input features to the model.
            out_features (int): Number of output features of the model
              (how many classes there are).
            hidden_units (int): Number of hidden units between layers, default 8.
        """
        super().__init__()
        self.linear_layer_stack = nn.Sequential(
            nn.Linear(in_features=input_features, out_features=hidden_units),
            #nn.ReLU(), # <- does our dataset require non-linear layers? (try uncommenting and see if the results change)
            #nn.Sigmoid(),
            nn.Linear(in_features=hidden_units, out_features=hidden_units),
            #nn.ReLU(), # <- does our dataset require non-linear layers? (try uncommenting and see if the results change)
            nn.Linear(in_features=hidden_units, out_features=output_features), # how many classes are there?
        )
    
    def forward(self, x):
        return self.linear_layer_stack(x)

# Calculate accuracy (a classification metric)
def accuracy_fn(y_true, y_pred):
    correct = torch.eq(y_true, y_pred).sum().item() # torch.eq() calculates where two tensors are equal
    acc = (correct / len(y_pred)) * 100 
    return acc

In [5]:
NUM_FEATURES = 60660
NUM_CLASSES = 3
device = "cpu"

# Create an instance of BlobModel and send it to the target device
model = MultiClassificationModel(input_features=NUM_FEATURES, 
                    output_features=NUM_CLASSES, 
                    hidden_units=8).to(device)
model

MultiClassificationModel(
  (linear_layer_stack): Sequential(
    (0): Linear(in_features=60660, out_features=8, bias=True)
    (1): Linear(in_features=8, out_features=8, bias=True)
    (2): Linear(in_features=8, out_features=3, bias=True)
  )
)

In [6]:
# Create loss and optimizer
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), 
                            lr=0.001) # exercise: try changing the learning rate here and seeing what happens to the model

In [7]:
# Perform a single forward pass on the data (we'll need to put it to the target device for it to work)
model(X_train_tens.to(device))[:5]

tensor([[  5.3309,  60.4203, -16.2986],
        [  9.0187, 102.5659,  -3.7891],
        [-23.3094,  65.5774, -31.0714],
        [-46.3397,  62.3671, -45.2362],
        [ 22.1226,  38.7476,  -7.6419]], grad_fn=<SliceBackward0>)

In [8]:
model(X_train_tens.to(device))[0].shape, NUM_CLASSES 

(torch.Size([3]), 3)

In [9]:
# Make prediction logits with model
y_logits = model(X_test_tens.to(device))

# Perform softmax calculation on logits across dimension 1 to get prediction probabilities
y_pred_probs = torch.softmax(y_logits, dim=1) 
print(y_logits[:5])
print(y_pred_probs[:5])

tensor([[  0.9766, 106.3172,  -9.6780],
        [ -2.2327,  62.3234, -21.7038],
        [-14.7883,  50.5043, -22.6019],
        [  3.4967,   6.3571, -30.9968],
        [-37.1034, -24.6716, -60.3328]], grad_fn=<SliceBackward0>)
tensor([[0.0000e+00, 1.0000e+00, 0.0000e+00],
        [9.1972e-29, 1.0000e+00, 3.2172e-37],
        [4.4036e-29, 1.0000e+00, 1.7799e-32],
        [5.4148e-02, 9.4585e-01, 5.6654e-17],
        [3.9895e-06, 1.0000e+00, 3.2549e-16]], grad_fn=<SliceBackward0>)


In [10]:
# Sum the first sample output of the softmax activation function 
torch.sum(y_pred_probs[0])

tensor(1., grad_fn=<SumBackward0>)

In [11]:
# Which class does the model think is *most* likely at the index 0 sample?
print(y_pred_probs[0])
print(torch.argmax(y_pred_probs[0]))

tensor([0., 1., 0.], grad_fn=<SelectBackward0>)
tensor(1)


In [12]:
# Fit the model
torch.manual_seed(42)

# Set number of epochs
epochs = 100

# Put data to target device
X_train_tens, y_train_tens = X_train_tens.to(device), y_train_tens.to(device)
X_test_tens, y_test_tens = X_test_tens.to(device), y_test_tens.to(device)

for epoch in range(epochs):
    ### Training
    model.train()

    # 1. Forward pass
    y_logits = model(X_train_tens) # model outputs raw logits 
    y_pred = torch.softmax(y_logits, dim=1).argmax(dim=1) # go from logits -> prediction probabilities -> prediction labels
    # print(y_logits)
    # 2. Calculate loss and accuracy
    #print("####", y_logits)
    #print("####", y_train_tens)
    loss = loss_fn(y_logits, y_train_tens) 
    #print("####loss", loss)
    acc = accuracy_fn(y_true=y_train_tens,
                      y_pred=y_pred)

    # 3. Optimizer zero grad
    optimizer.zero_grad()

    # 4. Loss backwards
    loss.backward()

    # 5. Optimizer step
    optimizer.step()

    ### Testing
    model.eval()
    with torch.inference_mode():
      # 1. Forward pass
      test_logits = model(X_test_tens)
      test_pred = torch.softmax(test_logits, dim=1).argmax(dim=1)
      # 2. Calculate test loss and accuracy
      test_loss = loss_fn(test_logits, y_test_tens)
      test_acc = accuracy_fn(y_true=y_test_tens,
                             y_pred=test_pred)

    # Print out what's happening
    if epoch % 1 == 0:
        print(f"Epoch: {epoch} | Loss: {loss:.5f}, Acc: {acc:.2f}% | Test Loss: {test_loss:.5f}, Test Acc: {test_acc:.2f}%") 
    if epoch+1 % 40 == 0:
        break

Epoch: 0 | Loss: 76.89359, Acc: 31.39% | Test Loss: 757577.50000, Test Acc: 10.19%
Epoch: 1 | Loss: 798421.93750, Acc: 8.52% | Test Loss: 807218053120.00000, Test Acc: 10.19%
Epoch: 2 | Loss: 821644296192.00000, Acc: 8.39% | Test Loss: 1806918533938090136829952.00000, Test Acc: 61.65%
Epoch: 3 | Loss: 1724170907594259439812608.00000, Acc: 59.25% | Test Loss: nan, Test Acc: 10.19%
Epoch: 4 | Loss: nan, Acc: 8.52% | Test Loss: nan, Test Acc: 10.19%
Epoch: 5 | Loss: nan, Acc: 8.52% | Test Loss: nan, Test Acc: 10.19%
Epoch: 6 | Loss: nan, Acc: 8.52% | Test Loss: nan, Test Acc: 10.19%
Epoch: 7 | Loss: nan, Acc: 8.52% | Test Loss: nan, Test Acc: 10.19%
Epoch: 8 | Loss: nan, Acc: 8.52% | Test Loss: nan, Test Acc: 10.19%
Epoch: 9 | Loss: nan, Acc: 8.52% | Test Loss: nan, Test Acc: 10.19%
Epoch: 10 | Loss: nan, Acc: 8.52% | Test Loss: nan, Test Acc: 10.19%
Epoch: 11 | Loss: nan, Acc: 8.52% | Test Loss: nan, Test Acc: 10.19%
Epoch: 12 | Loss: nan, Acc: 8.52% | Test Loss: nan, Test Acc: 10.19%
Ep

In [13]:
device = "cpu"

lr = 0.01
model = MultiClassificationModel(input_features=60660, output_features=3).to(device=device)
optimizer = torch.optim.SGD(model.parameters(), lr=lr)
loss_fn = nn.CrossEntropyLoss() #torch.nn.MSELoss()
n_epochs = 25

train_step = make_train_step(
    model=model,
    dataloader=train_dataloader,
    loss_fn=loss_fn,
    optimizer=optimizer,
    device=device,
)

val_step = make_val_step(
    model=model, dataloader=val_dataloader, loss_fn=loss_fn, device=device
)

train_losses = []
val_losses = []

for epoch in range(n_epochs):
    train_loss = train_step()
    train_losses.append(train_loss)

    val_loss = val_step()
    val_losses.append(val_loss)

    print(
        f"Epoch [{(epoch + 1):2}/{n_epochs:2}] | train loss: {train_loss:.4f} | validation loss: {val_loss:.4f}"
    )

NameError: name 'make_train_step' is not defined